# Generated by Django 5.2 on 2025-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='label',
            new_name='prediction',
        ),
        migrations.AddField(
            model_name='comment',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
